# -*- coding: utf-8 -*-
"""aitwin 1.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dYgWn7igwPt0sd4kK2EQW12Am7efFgee
"""

import os
from IPython.display import display, HTML

# Get list of all PNG files in /content/
png_files = [f for f in os.listdir('/content/') if f.endswith('.png')]

if not png_files:
    print("No PNG files found in the /content/ directory.")
    all_tasks = []
else:
    print(f"Found {len(png_files)} PNG files to process:")
    for i, file_name in enumerate(png_files):
        print(f"{i + 1}. {file_name}")

    # Store all paths and names for iteration in the next cells
    global png_tasks
    png_tasks = []
    for file_name in png_files:
        full_path = os.path.join('/content/', file_name)
        name_text = os.path.splitext(file_name)[0]
        png_tasks.append({'path': full_path, 'name': name_text})

    display(HTML(f"<p style='color:green;'><b>{len(png_tasks)} images ready. Please run the next cell to process all of them.</b></p>"))

from PIL import Image
import numpy as np
import os
import shutil
from google.colab import files

# -------------------------
# SETTINGS
# -------------------------
output_folder = "cropped_parts"
anchor = "center"        # "bottom", "center", or "top"
min_region_width = 15    # ignore noise regions narrower than this (px)
min_pixel_count = 50     # ignore regions with fewer than this many visible pixels total

# Ensure output folder is clean
if os.path.exists(output_folder):
    shutil.rmtree(output_folder)
os.makedirs(output_folder, exist_ok=True)

# Iterate over all tasks collected in the first cell
for task in png_tasks:
    input_image = task['path']
    base_name = task['name']

    print(f"\nProcessing: {input_image}...")

    try:
        img = Image.open(input_image).convert("RGBA")
        width, height = img.size
        alpha = np.array(img)[:, :, 3]

        # STEP 1: FIND CONTENT COLUMNS
        col_has_content = alpha.sum(axis=0) > 0
        regions = []
        in_region = False
        start = 0
        for x, has_content in enumerate(col_has_content):
            if has_content and not in_region:
                start = x
                in_region = True
            elif not has_content and in_region:
                regions.append((start, x))
                in_region = False
        if in_region:
            regions.append((start, len(col_has_content)))

        # STEP 2: FILTER OUT NOISE
        valid_regions = []
        for (left, right) in regions:
            region_width = right - left
            pixel_count = (alpha[:, left:right] > 0).sum()
            if region_width >= min_region_width and pixel_count >= min_pixel_count:
                valid_regions.append((left, right))

        # STEP 3 & 4: TIGHT-CROP AND FIND CANVAS SIZE
        tight_crops = []
        for (left, right) in valid_regions:
            part = img.crop((left, 0, right, height))
            bbox = part.getbbox()
            if bbox:
                tight_crops.append(part.crop(bbox))

        if not tight_crops:
            print(f"No character regions found in {input_image}.")
            continue

        canvas_w = max(c.width for c in tight_crops)
        canvas_h = max(c.height for c in tight_crops)

        # STEP 5: PASTE AND SAVE
        for i, crop in enumerate(tight_crops):
            canvas = Image.new("RGBA", (canvas_w, canvas_h), (0, 0, 0, 0))
            x = (canvas_w - crop.width) // 2
            if anchor == "bottom":
                y = canvas_h - crop.height
            elif anchor == "top":
                y = 0
            else:
                y = (canvas_h - crop.height) // 2

            canvas.paste(crop, (x, y), crop)
            filename = f"{base_name}_{i + 1:02d}.png"
            output_path = os.path.join(output_folder, filename)
            canvas.save(output_path, "PNG")

        print(f"Successfully saved {len(tight_crops)} frames for {base_name}.")

    except Exception as e:
        print(f"Error processing {input_image}: {e}")

# Final ZIP and Download
shutil.make_archive('all_cropped_images', 'zip', output_folder)
files.download('all_cropped_images.zip')
print("\nAll processing complete. Download started.")

import os
import glob
import shutil

# Identify all .png and .zip files in /content/
files_to_remove = glob.glob('/content/*.png') + glob.glob('/content/*.zip')

# Remove files
if not files_to_remove:
    print("No PNG or ZIP files found to delete.")
else:
    for f in files_to_remove:
        try:
            os.remove(f)
            print(f"Deleted file: {f}")
        except Exception as e:
            print(f"Error deleting file {f}: {e}")

# Remove the cropped_parts folder
folder_path = '/content/cropped_parts'
if os.path.exists(folder_path):
    try:
        shutil.rmtree(folder_path)
        print(f"Deleted folder: {folder_path}")
    except Exception as e:
        print(f"Error deleting folder {folder_path}: {e}")
else:
    print("Folder 'cropped_parts' not found.")

print("\nFull cleanup complete.")

